### ISSUE TITLE
"Captured quantified variables" error

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#146]
This is an older issue, but I wanted to move it here. The Cryptol code below causes all sorts of heck when loaded.

```
type Field fv =
  { field_zero : fv
  , field_unit : fv
  , is_equal : (fv, fv) -> Bit
  }

type AffinePoint fv = { x : fv, y : fv }

type ProjectivePoint fv = { x : fv, y : fv, z : fv }

type CurveOps fv gv = {
       field : Field fv
     , double : ProjectivePoint fv -> ProjectivePoint fv
     , add : (ProjectivePoint fv, AffinePoint fv) -> ProjectivePoint fv
     }

mk_curve_ops : {fv, gv} (Field fv, Field gv) -> CurveOps (fv, gv)
mk_curve_ops (f,g) = c
  where
    c = { field = f
        , double = \p -> ec_double(f, p)
        , add = \(p,q) -> ec_full_add(c, p, q)
        }

ec_double : {fv} (Field fv, ProjectivePoint fv) -> ProjectivePoint fv
ec_double(f,s) = { x = f.field_unit, y = f.field_unit, z = f.field_zero }

ec_full_add : {fv, gv}
    (CurveOps (fv, gv), ProjectivePoint fv, AffinePoint fv) -> ProjectivePoint fv
ec_full_add(p, s, t) =
  if is_zero(s.z) then
    { x = t.x
    , y = t.y
    , z = p.field.field_unit
    }
  else
      { x = p.field.field_unit
      , y = p.field.field_unit
      , z = p.field.field_zero 
      }
 where
   is_zero(x) = p.field.is_equal(x, p.field.field_zero)
```

Specifically:

```
Loading module Cryptol
Loading module Main
cryptol2: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  88983488fcdf9916eb18342b861b543ca2f8b1e5
  Branch:    master (non-committed files present during build)
  Location:  Cryptol.TypeCheck.Subst.apSubst (Schema)
  Message:   Captured quantified variables:
             Substitution: fromList [(TVFree 103 KType (fromList [TVBound 96 KType,TVBound 97 KType]) type of 0th tuple field,TRec [(Name "field",TUser (QName (Just (ModName ["Main"])) (Name "Field")) [TVar (TVBound 96 KType)] (TRec [(Name "field_zero",TVar (TVBound 96 KType)),(Name "field_unit",TVar (TVBound 96 KType)),(Name "is_equal",TCon (TC TCFun) [TCon (TC (TCTuple 2)) [TVar (TVBound 96 KType),TVar (TVBound 96 KType)],TCon (TC TCBit) []])])),(Name "double",TCon (TC TCFun) [TUser (QName (Just (ModName ["Main"])) (Name "ProjectivePoint")) [TVar (TVBound 96 KType)] (TRec [(Name "x",TVar (TVBound 96 KType)),(Name "y",TVar (TVBound 96 KType)),(Name "z",TVar (TVBound 96 KType))]),TUser (QName (Just (ModName ["Main"])) (Name "ProjectivePoint")) [TVar (TVBound 96 KType)] (TRec [(Name "x",TVar (TVBound 96 KType)),(Name "y",TVar (TVBound 96 KType)),(Name "z",TVar (TVBound 96 KType))])]),(Name "add",TCon (TC TCFun) [TCon (TC (TCTuple 2)) [TUser (QName (Just (ModName ["Main"])) (Name "ProjectivePoint")) [TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)] (TRec [(Name "x",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)),(Name "y",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)),(Name "z",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38))]),TUser (QName (Just (ModName ["Main"])) (Name "AffinePoint")) [TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)] (TRec [(Name "x",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)),(Name "y",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38))])],TUser (QName (Just (ModName ["Main"])) (Name "ProjectivePoint")) [TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)] (TRec [(Name "x",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)),(Name "y",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38)),(Name "z",TVar (TVFree 167 KType (fromList [TVBound 138 KType,TVBound 139 KType]) 1st type parameter
of expression Main::ec_full_add
at curve.cry:22:27--22:38))])])])]
             Schema:       Forall {sVars = [TParam {tpUnique = 96, tpKind = KType, tpName = Just (QName Nothing (Name "fv"))},TParam {tpUnique = 97, tpKind = KType, tpName = Just (QName Nothing (Name "gv"))}], sProps = [], sType = TCon (TC TCFun) [TCon (TC (TCTuple 3)) [TVar (TVFree 103 KType (fromList [TVBound 96 KType,TVBound 97 KType]) type of 0th tuple field),TUser (QName (Just (ModName ["Main"])) (Name "ProjectivePoint")) [TVar (TVBound 96 KType)] (TRec [(Name "x",TVar (TVBound 96 KType)),(Name "y",TVar (TVBound 96 KType)),(Name "z",TVar (TVBound 96 KType))]),TUser (QName (Just (ModName ["Main"])) (Name "AffinePoint")) [TVar (TVBound 96 KType)] (TRec [(Name "x",TVar (TVBound 96 KType)),(Name "y",TVar (TVBound 96 KType))])],TUser (QName (Just (ModName ["Main"])) (Name "ProjectivePoint")) [TVar (TVBound 96 KType)] (TRec [(Name "x",TVar (TVBound 96 KType)),(Name "y",TVar (TVBound 96 KType)),(Name "z",TVar (TVBound 96 KType))])]}
             Variables:    fromList [TVBound 96 KType]
%< --------------------------------------------------- 
```

**Comment by dylanmc** [comment]
There are two bugs here. Sean's original code produces this interesting error:

```
[warning] at ./ticket146.cry:11:6--11:14:
  Assuming  gv to have a numeric type
[error] at ./ticket146.cry:17:49--17:66:
  Incorrect type form.
    Expected: a value type
    Inferred: # -> *
[error] at ./ticket146.cry:22:39--22:40:
  The type ?n8 is not sufficiently polymorphic.
    It cannot depend on quantified variables: a`261
  where
  ?n8 is defintion of 'Main::p'
[error] at ./ticket146.cry:29:6--29:23:
  Incorrect type form.
    Expected: a value type
    Inferred: # -> *
```

**Comment by robdockins** [comment]
This bug seems to have been fixed at some point.  As @dylanmc noted, the original code now produces some errors instead of causing a panic.  The errors could maybe be improved, but they do at least point to the troublesome program points.

**Comment by brianhuffman** [comment]
I doubt this bug was ever fixed; the expected-failure file on the regression test has been there since 2014. Anyway, it's still failing today.

I added another explicit invariant check for the `InferM` monad to the `extendSubst` function in c1c80ce, which causes `T146.cry` to fail even earlier.
Old error message:
```
%< ---------------------------------------------------
  Revision:  50f54c9610ba07a79cb0952bebd5060ca4290ab5
  Branch:    master (uncommited files present)
  Location:  Cryptol.TypeCheck.Subst.apSubst (Schema)
  Message:   Captured quantified variables:
             Substitution: [?c33 := {v0 : a`859} -> a`859,
 ?d33 := {field : {v0 : a`862}, v1 : a`862, v2 : ?w33},
 ?f33 := {field : {v0 : a`862}, v1 : a`862, v2 : ?w33},
 ?g33 := a`862, ?h33 := {v0 : a`862},
 ?i33 := {field : {v0 : a`862}, v1 : a`862, v2 : ?w33},
 ?j33 := {v0 : a`862},
 ?k33 := {field : {v0 : a`862}, v1 : a`862, v2 : ?w33},
 ?l33 := {v0 : a`862} -> ?x33, ?m33 := {v0 : a`862}, ?n33 := ?x33,
 ?o33 := {v0 : a`862},
 ?p33 := {field : {v0 : a`862}, v1 : a`862, v2 : ?w33},
 ?q33 := {v0 : a`862}, ?r33 := a`862, ?s33 := ?w33,
 ?t33 := {v0 : a`862}, ?u33 := a`862,
 ?v33 := {field : {v0 : a`862}, v1 : a`862, v2 : ?w33}]
             Schema:       {fv} ?f33 -> fv
             Variables:    a`862
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.5.0-8gmvoYKVZwnH13JJzf5Zvm:Cryptol.Utils.Panic
  panic, called at src/Cryptol/TypeCheck/Subst.hs:231:19 in cryptol-2.5.0-8gmvoYKVZwnH13JJzf5Zvm:Cryptol.TypeCheck.Subst
%< ---------------------------------------------------
```
New error message:
```
%< ---------------------------------------------------
  Revision:  50f54c9610ba07a79cb0952bebd5060ca4290ab5
  Branch:    master (uncommited files present)
  Location:  Cryptol.TypeCheck.Monad.extendSubst
  Message:   Escaped quantified variables:
             Substitution:  [?g33 := a`862]
             Vars in scope: []
             Escaped:       [a`862]
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.5.0-8gmvoYKVZwnH13JJzf5Zvm:Cryptol.Utils.Panic
  panic, called at src/Cryptol/TypeCheck/Monad.hs:511:8 in cryptol-2.5.0-8gmvoYKVZwnH13JJzf5Zvm:Cryptol.TypeCheck.Monad
%< ---------------------------------------------------
```

**Comment by brianhuffman** [comment]
Fixed in ae091dbaa9d87a18d6c47ae2df02f15052e45b03.
